site_name: My Docs
nav:
  - LR1:
    - About: LR1/about.md
    - Database: LR1/db.md
    - Models: LR1/models.md
    - API: LR1/api.md
    - Authroization/Registration: LR1/auth.md

  - LR2:
    - Task 1: LR2/task1.md
    - Task 2: LR2/task2.md

  - LR3:
    - Task 1: LR3/task1.md
    - Task 2: LR3/task2.md
    - Task 3: LR3/task3.md

theme:
  material